export { AlmostTrueSegments, thunkAlmostTrueSegments } from './almostTrue'
export { BreatherSegments, thunkBreatherSegments } from './breather'
export { OtherSegments, thunkOtherSegments } from './other'
export { ThirtyfiveSegments, thunkThirtyfiveSegments } from './thirtyfive'
export { TrueSegments, thunkTrueSegments } from './true'
